// <auto-generated />
using ExternalSiteDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ExternalSiteDemo.Migrations
{
    [DbContext(typeof(ExternalSiteDemoContext))]
    partial class ExternalSiteDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExternalSiteDemo.Data.LabAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LabActionDescription");

                    b.Property<long>("LabInstanceId");

                    b.Property<int>("LabProfileId");

                    b.Property<string>("LabProfileName");

                    b.Property<string>("LastName");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("LabLaunch");
                });
#pragma warning restore 612, 618
        }
    }
}
